import { DELIVERY_METHODS } from '../data/deliveryMethods';
import { PAYMENT_BANKS } from '../data/paymentMethods';

export default function DeliveryPayments() {
  return (
    <section id="entregas" className="bg-[var(--ba-ivory)] px-5 py-24 sm:px-8 sm:py-32 lg:px-10">
      <div className="mx-auto max-w-[1240px]">
        <div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20"><div><p className="ba-kicker">Entregas y pagos</p><h2 className="ba-section-title mt-4">Recibe tu pedido como prefieras</h2><p className="ba-section-copy mt-5">Las opciones y costos disponibles se confirman dentro del carrito según el tipo de entrega seleccionado.</p></div><div className="grid gap-3 sm:grid-cols-2">{DELIVERY_METHODS.map((method, index) => <article key={method.value} className="group flex min-h-32 items-start gap-4 rounded-2xl border border-[var(--ba-border)] bg-[var(--ba-warm-white)] p-5 transition duration-200 hover:-translate-y-0.5 hover:border-[var(--ba-copper-soft)]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[var(--ba-navy)] text-xs font-bold text-white">0{index + 1}</span><div><h3 className="text-sm font-extrabold text-[var(--ba-navy-deep)]">{method.label}</h3><p className="mt-2 text-xs leading-5 text-[var(--ba-muted)]">Disponible para seleccionar dentro del carrito.</p></div></article>)}</div></div>
        <div className="mt-16 border-t border-[var(--ba-border)] pt-12"><h3 className="font-display text-3xl font-medium text-[var(--ba-navy-deep)]">Pagos claros y sin complicaciones</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--ba-muted)]">Para envíos puedes elegir transferencia o depósito. Los datos bancarios se comparten de forma privada al confirmar por WhatsApp.</p><div className="mt-7 grid gap-4 lg:grid-cols-2">{PAYMENT_BANKS.map((bank) => <article key={bank.value} className="flex min-h-28 items-center justify-between gap-5 rounded-2xl border border-[var(--ba-border)] bg-[var(--ba-warm-white)] p-5"><div className="min-w-0"><strong className="block text-base text-[var(--ba-navy-deep)]">{bank.label}</strong><span className="mt-2 block text-sm text-[var(--ba-muted)]">Transferencia o depósito</span></div><span className="flex h-12 w-36 shrink-0 items-center justify-center overflow-hidden"><img src={bank.logo} alt={`Logo de ${bank.label}`} width={bank.logoWidth} height={bank.logoHeight} loading="lazy" className={`shrink-0 object-contain ${bank.logoClassName}`} /></span></article>)}</div><p className="mt-5 text-sm text-[var(--ba-muted)]">El efectivo está disponible únicamente para retiro en el domicilio de la tienda. No mostramos datos bancarios sensibles en la web.</p></div>
      </div>
    </section>
  );
}
